config/routes.rb
Rails.application.routes.draw do
  resources :notifications do
    member do
      get :accept
      get :reject
    end
  end
  devise_for :users
  root to: "pages#home"
  resources :games do
    resources :bookings, only: %i[new create show]
  end
  get "profile", to: "profiles#show"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :authenticate_user!
  def show
    @user = current_user
    @bookings = []
    Booking.all.each do |booking|
      if booking.game.user == current_user
        @bookings << booking
      end
    end
  end
end

app/views/profiles/show.html.erb
<div class="container">
 <div class="text mb-4">
   <h2>Your games</h2>
  </div>

  <div class="container m-8">
   <div class="profile">
     <div class="row">
      <% @user.games.each do |game| %>
        <div class="col-sm-12 col-md-6 col-lg-4 mb-4">
            <% if game.image.key != nil %>
            <div class="text-white card card-has-bg click-col" style="background-image:url('<%= cl_image_path game.image.key %>');">
              <img class="card-img d-none" src="<%= cl_image_path game.image.key %>" alt="<%= game.name %>">
            <% else %>
            <div class="text-white card card-has-bg click-col" style="background-image:url('risk.jpeg');">
              <img class="card-img d-none" src="risk.jpeg" alt="<%= game.name %>">
            <% end %>
              <div class="card-img-overlay d-flex flex-column">
                <div class="card-body">
                  <small class="card-meta mb-2"><%= game.category %></small>
                  <h4 class="card-title mt-0"><% if current_user.games.include?(game) %>
                        <%= link_to game.name, game_path(game), class: "text-white" %>
                        <% else %>
                        <%= link_to game.name, new_game_booking_path(game), class: "text-white" %>
                        <% end %></h4>
                  <p><%= game.description %></p>
                  <small><i class="fa-solid fa-people-line"></i> <%= game.number_players %></small><br>
                  <small><i class="fa-solid fa-euro-sign ms-1 me-1"></i> <%= game.day_price %></small>
                </div>
                <div class="card-footer">
                  <div class="media">
                    <div class="media-body text-white">
                      <button id="card_link" class="btn btn-outline-warning btn-rounded my-2 my-sm-0 mr-3" type="submit"><% if current_user.games.include?(game) %>
                        <%= link_to "Edit and details", game_path(game), class: 'text-white' %>
                        <% else %>
                        <%= link_to 'Details and Booking', new_game_booking_path(game), class: 'text-white' %>
                        <% end %> </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
   </div>


    <div class="text">
      <h2>Your Requests</h2>
      <% @bookings.each do |booking| %>
        <div class="notification mt-3">
          <div class="notification-content">
          <h5> Booking was made by <%= booking.user.first_name %>, for the game : <%= booking.game.name %></h5>
          </div>
          <div class="notification-actions">
            <%= link_to "Accept", games_path, method: :put, class: "accept-btn" %>
            <%= link_to "Reject", games_path, method: :put, class: "reject-btn" %>
          </div>
        </div>
      <% end %>
    </div>



</div>