config/routes.rb
Rails.application.routes.draw do
  resources :notifications do
    member do
      get :accept
      get :reject
    end
  end
  devise_for :users
  root to: "pages#home"
  resources :games do
    resources :bookings, only: %i[new create show]
  end
  get "profile", to: "profiles#show"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true

  belongs_to :game
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit destroy]

    #test
  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
    @game =  Game.find(params[:game_id])
    @markers = [
      {
        lat: @game.user.latitude,
        lng: @game.user.longitude,
        info_window_html: render_to_string(partial: "games/info_window", locals: { game: @game }),
        marker_html: render_to_string(partial: 'games/marker', locals: { game: @game })
      }]
  end

  def edit
  end

  # def accept
  #   @booking = Booking.find(params[:id])
  #   @booking.status = "Accepted"
  #   @booking.save
  #   @booking.game.update(available: false)

  #   flash[:success] = "Booking request has been accepted."
  #   redirect_to games_path
  # end

  # def reject
  #   @booking = Booking.find(params[:id])
  #   @booking.status = "Decline"
  #   @booking.save

  #   @booking.user.notifications.create(
  #     message: "Your booking request for #{booking.game.name} has been rejected.",
  #     link: game_path(@booking.game)
  #   )

  #   flash[:success] = "Booking request has been rejected."
  #   redirect_to root_path
  # end

  def create

    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @game = Game.find(params[:game_id])
    @booking.game = @game
    respond_to do |format|
      if @booking.save
        Notification.create(user: @booking.game.user, game: @game, status: false)
        format.html { redirect_to profile_path, notice: 'Booking was successfully created.' }
        format.html { redirect_to booking.game.user.profile_path, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    if @booking.update(booking_params)
      redirect_to profile_path, notice: "Booking was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to profile_path, notice: "Booking was successfully destroyed."
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :game_id, :user_id)
  end
end

app/views/bookings/index.html.erb
<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>User</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.game.name %></td>
        <td><%= booking.user.email %></td>
        <td>
          <% if booking.confirmed %>
            Confirmed
          <% elsif booking.rejected %>
            Rejected
          <% else %>
            Pending
          <% end %>
        </td>
        <td>
          <% if booking.pending? %>
            <%= link_to "Accept", accept_booking_path(booking), method: :patch %>
            <%= link_to "Reject", reject_booking_path(booking), method: :patch %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<div class="container">
  <div class="product-wrapper">
    <div class="row">
      <div id="carouselExampleIndicators" class="carousel slide col-lg-7" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>

        <div class="carousel-inner">
          <% @game.images.each_with_index do |image, index| %>
            <div class="carousel-item carousel-photo <%= index == 0 ? 'active' : '' %>">
              <%= image_tag(image.url, class: 'd-block w-100') %>
            </div>
          <% end %>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <div class="col-lg-5 d-flex">
        <div class="d-flex flex-column align-items-center col-6 flex-grow-1 justify-content-center border border-secondary rounded-3 card_new_booking">
          <h2>Book <%= @game.name %>!</h2>
          <%= simple_form_for [@game, @booking] do |f| %>
          <div class="mb-3 mt-3">
            <%= f.label 'From' %>
            <%= f.input_field :start_date %>
          </div>
          <div>
            <%= f.label 'to', class: 'me-4 mb-4' %>
            <%= f.input_field :end_date %>
          </div>
          <div class="text-center">
            <%= f.button :submit, 'Book it', class: 'btn btn-warning' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
      <div class="row game_info_container">
        <div class="col card_game_info m-2">
          <h2>
            <%= @game.name %>
          </h2>
        </div>
        <div class="col-5 card_game_info m-2">
          <strong><%= @game.description %></strong>
        </div>
        <div class="col card_game_info m-2">
          <p>
            Price per day: €<%= @game.day_price %><br>
            Number of players: <%= @game.number_players %><br>
            Category: <%= @game.category %>
          </p>
        </div>
      </div>
    <div id='map' style='width: 100%; height: 300px;' data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  </div>
 </div>

app/views/bookings/show.html.erb
<div class="booking-cofirmation">
<h4>You have successfully booked <%= @booking.game.name %> Game </h4>
<ul>
<li> Details of this booking:</li>
</ul>
</div>